name: Java CI

on: [pull_request]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the master branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with gradle
        run: ./gradlew clean compileTestScala
      - name: Run tests with timeout
        timeout-minutes: 10
        run: ./gradlew test
