name: Compiler

on: [ pull_request, merge_group ]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./mill flix.test.compile
      - name: Run tests with timeout
        timeout-minutes: 20
        run: ./mill flix.test.testOnly ca.uwaterloo.flix.TestAll
