name: Fuzz Compiler

on: [ pull_request, merge_group ]

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: fuzzing-${{ github.ref }}

jobs:
  build-and-fuzz:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./mill clean && ./mill flix.test.compile
      - name: Fuzz with timeout
        timeout-minutes: 20
        run: ./mill flix.testFuzzerSuite
