name: Package Manager

on: [ pull_request, merge_group ]

permissions:
  contents: read

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: test-flix-package-manager-${{ github.ref }}

jobs:
  build-and-test-pkg-man:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build
        run: ./mill flix.test.compile
      - name: Test Package Manager suite with timeout
        env: # Only add token in this step to prevent other steps from abusing the token
          GITHUB_CI_RUNNER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
        run: ./mill flix.testPackageManager
